;; -*- lexical-binding: t; -*-

(defconst custom/color-black "#696688")
(defconst custom/color-bright-black "#716ba1")
(defconst custom/color-red "#B85868")
(defconst custom/color-bright-red "#C96878")
(defconst custom/color-green "#6E8A4A")
(defconst custom/color-bright-green "#82A056")
(defconst custom/color-yellow "#B58820")
(defconst custom/color-bright-yellow "#C99528")
(defconst custom/color-blue "#4F77A8")
(defconst custom/color-bright-blue "#6088B8")
(defconst custom/color-magenta "#8E5A98")
(defconst custom/color-bright-magenta "#9F6AA8")
(defconst custom/color-cyan "#4A8A85")
(defconst custom/color-bright-cyan "#5AA098")
(defconst custom/color-white "#C8BFAE")
(defconst custom/color-bright-white "#DED7C5")
(defconst custom/color-background "#FFFCEF")
(defconst custom/color-dark-background "#F5EFDD")
(defconst custom/color-region "#F5EFDD")

(provide 'colors)
